# Generated by Django 4.1.3 on 2022-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/images/users/default.png', upload_to='media/images/users/'),
        ),
    ]
