# Generated by Django 4.1.3 on 2022-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='BookTag',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishable',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/books'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
