# Generated by Django 4.1.3 on 2022-11-15 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0002_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[(1, 'Book'), (2, 'Page')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.page')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
