# Generated by Django 4.1.3 on 2022-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0003_pagereview_page_alter_book_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='media/images/pages'),
        ),
    ]
