# Generated by Django 4.1.3 on 2022-12-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstack', '0004_bookviews_alter_activity_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='pages/thumbnail', verbose_name='عکس کوچک شده'),
        ),
    ]
