# Generated by Django 4.1.3 on 2022-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0005_alter_activity_created_at_alter_page_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Shelve',
            new_name='shelve',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted')], max_length=1),
        ),
    ]
