# Generated by Django 4.1.3 on 2022-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0006_rename_shelve_activity_shelve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
