# Generated by Django 4.1.3 on 2022-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0008_book_views_count_bookviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='images/default_book.jpg', upload_to='images/books/thumbnail/'),
        ),
        migrations.AddField(
            model_name='shelve',
            name='thumbnail',
            field=models.ImageField(default='images/default_shelve.jpg', upload_to='images/shelve/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/default_book.jpg', upload_to='images/books/'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='image',
            field=models.ImageField(default='images/default_shelve.jpg', upload_to='images/shelves/'),
        ),
    ]
