# Generated by Django 4.1.3 on 2022-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstack', '0010_rename_publish_book_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-name',), 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-created_at',), 'verbose_name': 'فصل', 'verbose_name_plural': 'فصول'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('id',), 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحات'},
        ),
        migrations.AlterModelOptions(
            name='shelve',
            options={'ordering': ('-name',), 'verbose_name': 'قفسه', 'verbose_name_plural': 'قفسه ها'},
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
