# Generated by Django 4.1.3 on 2022-12-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstack', '0011_alter_book_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',), 'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت ها'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted')], max_length=1, verbose_name='نوع فعالیت'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstack.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='model_type',
            field=models.CharField(choices=[('shelve', 'Shelve'), ('book', 'Book'), ('page', 'Page')], max_length=6, verbose_name='نوع مدل'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstack.page', verbose_name='صفحه'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='shelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstack.shelve', verbose_name='قفسه'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/default_book.jpg', upload_to='images/books/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=25, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstack.shelve', verbose_name='قفسه'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='bookstack.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=70, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='bookstack.chapter', verbose_name='قفسه'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='images/pages/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='page',
            field=models.ManyToManyField(to='bookstack.page', verbose_name='صفحه'),
        ),
        migrations.AlterField(
            model_name='pagereview',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='pagereview',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookstack.page', verbose_name='صفحه'),
        ),
        migrations.AlterField(
            model_name='pagereview',
            name='text',
            field=models.CharField(max_length=255, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='pagereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='image',
            field=models.ImageField(default='images/default_shelve.jpg', upload_to='images/shelves/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام قفسه'),
        ),
        migrations.AlterField(
            model_name='shelve',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='بر چسب ها'),
        ),
    ]
