# Generated by Django 4.1.3 on 2022-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_shelveimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelve',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/shelves'),
        ),
        migrations.DeleteModel(
            name='shelveImage',
        ),
    ]
